src/article-counter-crud/create.html, src/article-counter-crud/create.js, src/article-counter-crud/data-form.js, src/article-motif-crud/create.html, src/article-motif-crud/create.js, src/article-motif-crud/data-form.html, src/article-motif-crud/data-form.js, src/article-motif-crud/edit.html, src/article-motif-crud/edit.js, src/storage-crud/create.html, src/storage-crud/data-form.html, src/storage-crud/data-form.js, src/storage-crud/edit.html, src/storage-crud/edit.js, src/transfer-in-cr/create.html, src/transfer-in-cr/create.js, src/transfer-in-cr/data-form.html, src/transfer-in-cr/data-form.js, src/transfer-out-cr/create.html, src/transfer-out-cr/create.js, src/transfer-out-cr/data-form.html, src/transfer-out-cr/data-form.js
=> Add Validation for UI

src/app.js, src/efr-tb-sab-cr/create.html, src/efr-tb-sab-cr/create.js, src/efr-tb-sab-cr/data-form.html, src/efr-tb-sab-cr/data-form.js, src/efr-tb-sab-cr/index.html, src/efr-tb-sab-cr/index.js, src/efr-tb-sab-cr/list.html, src/efr-tb-sab-cr/list.js, src/efr-tb-sab-cr/service.js, src/efr-tb-sab-cr/view.html, src/efr-tb-sab-cr/view.js
create view for finishing terima komponen
=> create view for finishing terima komponen

src/app.js, src/efr-hp-fng-cr/create.html, src/efr-hp-fng-cr/create.js, src/efr-hp-fng-cr/data-form.html, src/efr-hp-fng-cr/data-form.js, src/efr-hp-fng-cr/index.html, src/efr-hp-fng-cr/index.js, src/efr-hp-fng-cr/list.html, src/efr-hp-fng-cr/list.js, src/efr-hp-fng-cr/service.js, src/efr-hp-fng-cr/view.html, src/efr-hp-fng-cr/view.js, src/efr-kb-exb-cr/data-form.html, src/efr-tb-sab-cr/create.js
=> merge modul

src/efr-tb-bat-cr/create.js, src/efr-tb-bat-cr/index.js, src/efr-tb-bat-cr/list.html, src/efr-tb-bat-cr/pending.html, src/efr-tb-bat-cr/pending.js, src/efr-tb-bat-cr/service.js, src/efr-tb-bbt-cr/create.js, src/efr-tb-bbt-cr/index.js, src/efr-tb-bbt-cr/list.html, src/efr-tb-bbt-cr/list.js, src/efr-tb-bbt-cr/pending.html, src/efr-tb-bbt-cr/pending.js, src/efr-tb-bbt-cr/service.js
list pending SPK dan auto fill create form Transfer in
=> ui list pending SPK

src/customs/elements/horsey.html, src/customs/elements/horsey.js, src/efr-kb-exb-cr/create.js, src/efr-kb-exb-cr/data-form.html, src/efr-kb-exb-cr/data-form.js, src/efr-kb-exb-cr/service.js
update horsey and UI for expedition
=> update horsey and UI for expedition

src/efr-kb-fng-cr/create.html, src/efr-kb-fng-cr/data-form.html, src/efr-kb-fng-cr/data-form.js, src/efr-kb-fng-cr/list.html, src/efr-kb-fng-cr/service.js, src/efr-kb-fng-cr/view.html, src/efr-tb-bjb-cr/create.html, src/efr-tb-bjb-cr/data-form.html, src/efr-tb-bjb-cr/data-form.js, src/efr-tb-bjb-cr/list.html, src/efr-tb-bjb-cr/view.html
delete remove and add item and modified display source and destination n in efr-tb-bjb
=> delete remove and add item and modified display source and destination n in efr-tb-bjb

src/modules/laporan/laporan-stok-ro/index.html, src/modules/laporan/laporan-stok-ro/index.js, src/modules/laporan/laporan-stok-ro/report.html, src/modules/laporan/laporan-stok-ro/report.js, src/modules/laporan/laporan-stok-ro/service.js, src/routes/laporan.js
Laporan Stok Berdasarkan Realisasi Order
=> Laporan Stok Berdasarkan Realisasi Order

src/modules/laporan/laporan-stok-ro/report.js, src/modules/laporan/laporan-stok-ro/service.js
=> update laporan stok berdasarkan realisasi order

src/modules/laporan/laporan-stok-ro/service.js
=> update report stok realisasi order

src/modules/merchandiser/product/data-form.html
disable harga jual domestik dan internasional ketika ingin mengubah
produk
=> update edit produk

src/routes/laporan.js
=> update route laporan

src/modules/auth/account/list.html, src/modules/auth/account/list.js, src/modules/daily-omzet/report.html, src/modules/daily-omzet/report.js
Add 1 more table for general selling
=> Daily Omzet Revision

src/modules/daily-omzet/report.html, src/modules/daily-omzet/report.js
=> Update Omset Harian

src/modules/daily-omzet/report.html, src/modules/daily-omzet/report.js
Reverts danliris/bateeq-ui#266
=> Revert "Update Omset Harian"

src/modules/stock-opname/view.js
=> update stock upname

src/modules/stock-opname/view.js
=> update stok opname

src/modules/stock-opname/view.js
Reverts danliris/bateeq-ui#274
=> Revert "update stok opname"

src/routes/auth.js
Give new Rule permission to AUTH with code C.01
=> update router on AUTH menu

src/modules/laporan-stok-akhir-bulan/dialogs/stock-in-storage-dialog.html
=> Add sortable column to view 2

src/modules/daily-omzet-1/report.html
Pembetulan Untuk judul omset kemarin
=> Pembetulan Untuk judul omset kemarin

src/modules/laporan/laporan-stok-ro/report.js
update error message must be gone if new search
=> Task 1 v1.0.0

src/modules/laporan/laporan-stok-ro/report.js
validation for xls generate for RO code mandatory
=> update v1 Task report per RO

src/modules/keuangan/list.html, src/modules/penjualan/list.html, src/modules/produk-pakaian/list.html, src/modules/target-omset/list.html
untuk:
1. Target omset
2. Penjualan
3. keuangan
4 produk pakaian
=> update list html for power BI

src/modules/keuangan/view.html, src/modules/penjualan/view.html, src/modules/produk-pakaian/view.html, src/modules/target-omset/view.html
update for response on safari for full screen button:
1. Keuangan,
2. Penjualan,
3. Produk-Pakaian, dan
4. Target-Omset.
Menu Dashboard
=> update power BI

index.html, src/modules/keuangan/view.html, src/modules/keuangan/view.js, src/modules/penjualan/view.html, src/modules/penjualan/view.js, src/modules/produk-pakaian/view.html, src/modules/produk-pakaian/view.js, src/modules/target-omset/view.html, src/modules/target-omset/view.js, src/utils/ios-fullscreen.js
1. module keuangan
2. module penjualan
3. module produk-pakaian
4.module target-omset
=> update for display full screen on ios

src/modules/daily-product-sales-product-1/index.html, src/modules/daily-product-sales-product-1/index.js, src/modules/daily-product-sales-product-1/report.html, src/modules/daily-product-sales-product-1/report.js, src/modules/daily-product-sales-product-1/service.js, src/routes/report.js
Pak Edo, berikut saya tambahkan aplikasi penjualan produk kemarin.
mohon diUAT kan Pak
Terimakasih
=> Penjualan Produk hari kemarin

src/modules/penjualan/list.js
=> Embed powerbi reports

src/modules/penjualan/list.js
PENJUALAN OMZET BERDASARKAN KOLEKSI (QUARTER)
=> Add embed powerbi report

src/modules/design-tracking/dialog-view/board-form-view.html
Edit board show numbefOfStage value
=> Fix design tracking CRUD after testing on dev

src/modules/daily-product-sales-product-1/index.js, src/modules/daily-product-sales-product-1/report.html
Edit title penjualan kemarin (per produk)
Mohon bantuannya cek kembali Pak Edo
Terimakasih
=> Edit title penjualan kemarin (per produk)

src/main.js
=> Change API location

src/modules/auth/account/data-form.html, src/modules/auth/account/data-form.js, src/modules/auth/account/profile.html, src/modules/auth/account/profile.js
1. Password should only displayed on create account
2. Fix css on account and profile form
=> Fix user matrix

src/modules/auth/account/edit.js
Assign password and confirm password
=> Fix edit not working

src/modules/design-tracking-reason/create.html, src/modules/design-tracking-reason/create.js, src/modules/design-tracking-reason/data-form.html, src/modules/design-tracking-reason/data-form.js, src/modules/design-tracking-reason/edit.html, src/modules/design-tracking-reason/edit.js, src/modules/design-tracking-reason/index.html, src/modules/design-tracking-reason/index.js, src/modules/design-tracking-reason/list.html, src/modules/design-tracking-reason/list.js, src/modules/design-tracking-reason/service.js, src/modules/design-tracking-reason/view.html, src/modules/design-tracking-reason/view.js, src/modules/design-tracking/board.html, src/modules/design-tracking/board.js, src/modules/design-tracking/core-service.js, src/modules/design-tracking/design.html, src/modules/design-tracking/dialog-view/board-form-view.html, src/modules/design-tracking/dialog-view/board-form-view.js, src/modules/design-tracking/dialog-view/design-form-view.html, src/modules/design-tracking/dialog-view/design-form-view.js, src/modules/design-tracking/styles/board-style.css, src/routes/designer.js
Modification:
1. Remove number of stage limiter
2. Make 8 stage css color
3. Add article counter
=> Add design tracking reason & modify design tracking

src/modules/daily-omzet/report.html, src/modules/daily-omzet/report.js
Berikut untuk module UI nya Pak Edo,
yang digunakan yang revisi untuk omset harian, yang "**Report omset harian (tambahan keterangan)**"
mohon dihapus..
Terimakasih
Andrew
=> UI- Omset harian terdapat keterangan di Penjualan Umum

src/modules/daily-omzet/report.html, src/modules/daily-omzet/report.js
Dear Pak Edo Mohon untuk menambah  keterangan di Penjualan VVIP
Terimakasih
Andrew
=> Penjualan VVIP menambah keterangan

src/modules/daily-omzet-1/report.html, src/modules/daily-omzet-1/report.js
Dear pak Edo
mohon cek request
Daily Omzet -1 tambah keterangan
=> Daily Omzet -1 tambah keterangan

src/modules/daily-omzet-1/report.js
=> daily-omzet-1

src/modules/purchasing/unit-receipt-note/data-form.js
=> update: Data Form

src/loader/division-loader.js, src/loader/storage-loader.js, src/loader/unit-receipt-note-loader.js, src/modules/purchasing/unit-payment-order/create/create.html, src/modules/purchasing/unit-payment-order/create/create.js, src/modules/purchasing/unit-payment-order/data-form.html, src/modules/purchasing/unit-payment-order/data-form.js, src/modules/purchasing/unit-payment-order/edit/edit.html, src/modules/purchasing/unit-payment-order/edit/edit.js, src/modules/purchasing/unit-payment-order/index.html, src/modules/purchasing/unit-payment-order/index.js, src/modules/purchasing/unit-payment-order/list/list.html, src/modules/purchasing/unit-payment-order/list/list.js, src/modules/purchasing/unit-payment-order/service.js, src/modules/purchasing/unit-payment-order/template/unit-payment-order-item.html, src/modules/purchasing/unit-payment-order/template/unit-payment-order-item.js, src/modules/purchasing/unit-payment-order/template/unit-receipt-note-item.html, src/modules/purchasing/unit-payment-order/template/unit-receipt-note-item.js, src/modules/purchasing/unit-payment-order/view/view.html, src/modules/purchasing/unit-payment-order/view/view.js, src/routes/purchasing.js
=> update storage loader

package.json
Version 1.7.0 still had problem
=> Fallback aurelia-binding version

package.json
latest version this dependencies get defect
=> remove ^ for getting latest version

src/modules/master-plan/booking-order/confirm.js, src/modules/master-plan/booking-order/create.js, src/modules/master-plan/booking-order/data-form.html, src/modules/master-plan/booking-order/edit.js, src/modules/master-plan/booking-order/list.html, src/modules/master-plan/booking-order/list.js, src/modules/master-plan/booking-order/service.js, src/modules/master-plan/booking-order/templates/booking-order-detail-footer.js, src/modules/master-plan/booking-order/templates/booking-order-detail.html, src/modules/master-plan/booking-order/templates/booking-order-detail.js, src/modules/master-plan/booking-order/view.js, src/routes/master.js, src/routes/masterplan.js
1. Add confirm dialog on confirm booking order
2. Add delete remaining functionality
3. Change format of date on list
4. Change cancelRemaining to setRemainingOrderQuantity for deleteRemaining and cancelRemaining functionality
5. Revamp button allowed on view
=> Booking Order Revision

src/modules/master-plan/blocking-plan-sewing/templates/detail-confirm.html, src/modules/master-plan/blocking-plan-sewing/templates/detail-confirm.js
- Md telah menambah detail ini
- Md telah menghapus detail ini
- Save is AddNew
=> Blocking Plan Sewing -  Booking Ada Perubahan

src/modules/master-plan/blocking-plan-sewing/data-form.html, src/modules/master-plan/blocking-plan-sewing/templates/detail-confirm.html, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/master-plan/booking-order/templates/booking-order-detail.js
- Save Update Blocking Plan Sewing (Sebelumnya kalau di cancel, update tetap berjalan)
-  Status di Blocking Sewing warna Merah
=> Blocking Plan Sewing && Booking Order - Status

src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.js
isConfirmed display and isConfirmed when have no value default to false
=> update ui for workschedules

src/components/dialog/confirm.html, src/components/dialog/confirm.js, src/components/dialog/dialog.js, src/loader/counter-search-loader.js, src/loader/style-search-loader.js, src/modules/master-plan/blocking-plan-sewing/data-form.html, src/modules/master-plan/blocking-plan-sewing/data-form.js, src/modules/master-plan/blocking-plan-sewing/index.js, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.js
-  Menambah message box sebelum menambah ro pada schedules, dengan kondisi RO  sudah ada atau belum ada
=> bateeq ui -  Blocking plan sewing - work schedule (add)

src/components/dialog/confirmRO.html, src/components/dialog/confirmRO.js, src/components/dialog/dialog.js, src/loader/counter-search-loader.js, src/loader/style-search-loader.js, src/modules/master-plan/blocking-plan-sewing/data-form.html, src/modules/master-plan/blocking-plan-sewing/data-form.js, src/modules/master-plan/blocking-plan-sewing/index.js, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.js
=> Blocking Plan Sewing - Add Jadwal Pengerjaan - Manual && Auto Save RO

src/modules/master-plan/blocking-plan-sewing/data-form.html, src/modules/master-plan/blocking-plan-sewing/data-form.js, src/modules/master-plan/blocking-plan-sewing/edit.js, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/merchandiser/cost-calculation-retail/view.js
Kondisi ReadOnly = True Ketika IsHasRo = False dan sebaliknya;
dengan tambahan Parameter di WorkSchedule
=> Blocking Plan - Create - Read Only

src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.js
Blocking Plan Sewing - ReadOnly When Edit
=> Blocking Plan Sewing - ReadOnly When Edit

src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.html, src/modules/master-plan/blocking-plan-sewing/templates/work-schedule.js
When Blocking Plan Sewing Add New  Confirm set 'Tidak'  or 'Ya'
=> Blocking Plan Sewing - Add New

src/modules/stock-opname/data-form.html, src/modules/stock-opname/data-form.js, src/modules/stock-opname/template/item.html, src/modules/stock-opname/template/item.js
=> Stock Opname - Check All

src/au-components/form/collection/collection.js, src/modules/stock-opname/data-form.html, src/modules/stock-opname/data-form.js, src/modules/stock-opname/template/item.html, src/modules/stock-opname/template/item.js
bateeq-UI - Stock Opname - Check All
=> bateeq-UI - Stock Opname - Check All

src/modules/stock-opname/template/item.js
=> Stock Opname - Remark

src/modules/stock-opname/template/item.js
1. stock opname remark
2. update inside remark
=> update stock opname

src/routes/masterplan.js
PIC.01 for master minggu and blocking plan & MRD.01 for booking order
=> update permission for master plan user

src/modules/efr-kb-rtt-cr/list.js, src/modules/efr-kb-rtt-cr/view.js, src/modules/merchandiser/cost-calculation-garment/data-form.js, src/modules/merchandiser/cost-calculation-retail/data-form.js, src/modules/packing-list-tt/index.html, src/modules/packing-list-tt/index.js, src/modules/packing-list-tt/list.html, src/modules/packing-list-tt/list.js, src/modules/packing-list-tt/service.js, src/modules/packing-list-tt/view.html, src/modules/packing-list-tt/view.js, src/routes/gudang-pusat.js
mengubah list di efr-kb-rtt-cr,menambah menu packing list transfer stock gudang,  menambah keyword OL U, OL U, OTL 1 U, OTL 2 U,  OL R, OTL 1 R, OTL 2 R, OTL 3 R
=> packinglist_transfer_stock, merchandiser

src/modules/storage-inventory/view.html
adanya penomoroan di item detail aliran stock
=> view detail aliran stock

src/modules/storage-inventory/service.js, src/modules/storage-inventory/view.html, src/modules/storage-inventory/view.js
=> Paging in Detail Aliran Stock

src/modules/merchandiser/cost-calculation-garment/view.html, src/modules/merchandiser/cost-calculation-garment/view.js
, Add var TotOTL1OTL2, Add Total (OL+OTL1+OTL2)
=> update View Cost Calculation Garment

src/modules/efr-kb-exp-cr/data-form.js, src/modules/efr-kb-exp-cr/template/packing-list.html, src/modules/efr-kb-exp-cr/template/packing-list.js, src/modules/efr-kb-exp-cr/view.js, src/modules/efr-kb-rtt-cr/view.js, src/modules/efr-tb-bbt-cr/data-form.html, src/modules/efr-tb-bbt-cr/data-form.js, src/modules/packing-list-cr/data-form.js, src/modules/packing-list-cr/view.html
=> update quantity binding

src/modules/efr-kb-rtp-cr/view.html, src/modules/efr-kb-rtt-cr/view.js
=> Ubah nama EFRATA jadi BATEEQ

src/modules/efr-kb-rtp-cr/data-form.html, src/modules/efr-kb-rtt-cr/data-form.html, src/modules/efr-kb-rtu-cr/data-form.html, src/modules/packing-list-cr/data-form.html
=> Fix UI Gudang and TOKO

src/modules/efr-kb-rtt-cr/view.html
=> update transfer stock

src/modules/collect/omzet/index.html, src/modules/collect/omzet/index.js, src/modules/collect/omzet/report.html, src/modules/collect/omzet/report.js, src/modules/collect/omzet/service.js, src/routes/collect.js, src/routes/index.js, src/side-nav-bar.html, src/utils/rest-service.js
=> add module collect data
